### ISSUE TITLE
ゲーム終了条件と判定を設定する

### ISSUE THREAD

**Issue by jochaken** [JoeTakasuna/KomatsuBlokus#14]
1. 両方パス状態になったら終了
2. 置いたブロックのマスの総数が多い方の勝ち

これで出来そう
つまり#5 が完成してから

**Comment by JoeTakasuna** [comment]
つまり#5 が完成してから開発できる

**Comment by jochaken** [comment]
勝ち負けと同時に得点も表示したいね

**Comment by jochaken** [comment]
マスの総数は①進行中に足していくか②最後に数えるかがあるけど、
②はゲーム中に得点表示できないし汎用性も低くなるから①で！
