### ISSUE TITLE
選択したブロックと向きで置けない時はエラー&再選択を出したい

### ISSUE THREAD

**Issue by jochaken** [JoeTakasuna/KomatsuBlokus#4]

**Comment by jochaken** [comment]
#5 と一緒に考えると良さそう

**Comment by jochaken** [comment]
- ブロック確定する前に探索させて、それで置ける場所0ならやり直し
- 時間かかるようになりそうだから探索スピードアップが必要かも（このイシューでは考えなくてok）

**Comment by JoeTakasuna** [comment]
- 後者は#48 で解決する

**Comment by jochaken** [comment]
スピードアップに関しては#48 に分けたから、
とりあえず動くものを作る部分を優先で！

**Comment by yushun1023** [comment]
checkBlockの中にrotatedBlockShapeを導入
「使用済みBlockの判定」のタイミングの修正-checkBlockがtrueの時に

**Comment by jochaken** [comment]
これを通じて#12 が解決された

**Comment by jochaken** [comment]
バグ直してねー
![image](https://user-images.githubusercontent.com/38747501/59891370-e17d0d00-940f-11e9-9563-568d26b29c69.png)

**Comment by jochaken** [comment]
- 枠の部分は検索しないようにした
- その為、`out index of range`エラーより先に枠部分でCANTSET判定が行われてFALSEを返すようになったから上記エラーも解決

**Comment by jochaken** [comment]
- 逆に上左にはみ出す時に`[-1]`となるのも結局枠を参照するから問題なし
