### ISSUE TITLE
モンテカルロ木探索を理解する

### ISSUE THREAD

**Issue by jochaken** [JoeTakasuna/KomatsuBlokus#40]
## 概要
- #30 を解決する為のアルゴリズムを勉強する
- 囲碁AIに用いられる手法

http://blog.brainpad.co.jp/entry/2018/04/05/163000

## こんなに早く始める理由
- #30 の前に#13 を作るが、更にその前に#4 や#5 等が必要
- その為、それらが出来るまでこれを先行して進める

**Comment by jochaken** [comment]
## 概要
- ゲーム木にモンテカルロ法を適用した探索アルゴリズム
- ゲーム進行の分岐に対して勝ち負けを報酬とし、それを分岐ごとに分配して良い手を探す

![a](https://user-images.githubusercontent.com/38747501/59321369-b65a3580-8d0c-11e9-9a46-1b7fe22c58aa.png)

**Comment by jochaken** [comment]
## ゲーム木とは
> 囲碁や将棋やリバーシのようなゲームは、交互に手を選択し、選択した手によって状況が変化していきます。このようなゲームでは、ゲーム木という表現ができます。

## モンテカルロ法とは（もしかしたら正しい理解じゃないかも）
> 強化学習のアルゴリズムの一種。とにかく何らかの報酬が得られるまで行動をしてみて、その報酬値を知ってから、辿ってきた状態と行動に対してその報酬を分配していきます。

**Comment by JoeTakasuna** [comment]
## モンテカルロ法とは
> 数値計算手法の一つで、乱数を用いた試行を繰り返すことにより近似解を求める手法。確率論的な事象についての推定値を得る場合を特に「モンテカルロシミュレーション」と呼ぶ。

**Comment by JoeTakasuna** [comment]
## ゲーム木とモンテカルロ法を組み合わせる理由
![b](https://user-images.githubusercontent.com/38747501/59321470-1fda4400-8d0d-11e9-8a80-05d2f68d03fd.png)

**Comment by JoeTakasuna** [comment]
> ## ゲーム木とモンテカルロ法を組み合わせる理由
> ### 3目並べのゲーム木
> ![b](https://user-images.githubusercontent.com/38747501/59321470-1fda4400-8d0d-11e9-8a80-05d2f68d03fd.png)
> 
> > ゲーム木は上から下に読んでいきます。図で状況を表している部分が「ノード」、「ノード」と「ノード」を繋いでいる線の部分が「エッジ」です。一番上のノードを「根ノード（root node）」と呼びます（図の赤い部分）。下の方にある緑の部分では、×が３つ並んでおり、後手の勝ちとなっています。勝敗がついているため、このノードはゲームの終着点であり、このノードから出ていくエッジはありません。このような末端のノードを「葉ノード（leaf node）」と呼びます。
> 
### ゲーム木複雑性という指標
> 途中で省略せず、全ての分岐を葉ノードまで展開したゲーム木のことを完全ゲーム木と呼びます。完全ゲーム木を書くことができれば、そのゲームがどんな風に展開していくのかを全て知ることができるので、そのゲームは先手必勝なのか、後手必勝なのかもわかりますし、実際に勝つための手順も完全に理解することができます。完全ゲーム木の葉ノードが多ければ多いほど、ゲーム展開の分岐が多い複雑なゲームであると解釈することができるため、完全ゲーム木の葉ノードの数をゲーム木複雑性と呼び、ゲームの複雑度の一つの指標とされます。

### 不完全なゲーム木で判断する
> 3目並べのゲーム木複雑性は26,830だそうです。省略せずに書き切って、完全解析できる量ではありますが、このブログに乗せるには大きすぎる数ですね。これもWikipediaの情報ですが、オセロだと10の58乗、チェスだと10の123乗、将棋だと10の226乗、囲碁では10の400乗と見積もられるようです。ここまで複雑なゲームだと、完全ゲーム木を書いて完全解析するというのは、現実的ではないですね。

> そのため、ゲーム木の考えは使いつつ、不完全なゲーム木でより正確な判断をすることが重要となります。ある局面で次に何を指すべきか、パッと有望な候補を絞り込み、その手が本当に有望なのかを、妥当であろう手の応酬である程度盤面を進めてみて、数手後の盤面がどちらにとって有利かという盤面の価値を正確に判断する。そのような能力が求められるわけです。

**Comment by jochaken** [comment]
## 強化学習とは
> 強化学習は機械学習のひとつの大きな分野で、試行錯誤を通じて「価値を最大化するような行動」を学習するものです。
教師付き学習とよく似た問題設定ですが、与えられた正解の出力をそのまま学習すれば良いわけではなく、もっと広い意味での「価値」を最大化する行動を学習しなければなりません。

## 報酬とは
> 強化学習では、与えられた「環境」における価値（あるいは「利益」と呼びます）を最大化するように「エージェント」を学習させます。
例えば、「テトリス」が環境で、そのプレイヤーがエージェントです。

![c](https://user-images.githubusercontent.com/38747501/59322643-130c1f00-8d12-11e9-9841-7e82d3494ef8.png)

> 状態とは、環境が今どうなっているのかをあらわすものです。株の売買の例では、各株式の今の値段や、持っている株式の数が状態にあたります。
行動とは、エージェントが環境に対してどのような行動を起こすことができるのかをあらわします。株の売買の例では、株の売り買いの判断やその量にあたります。
報酬とは、ある状態においてエージェントが行動を起こした結果、どれくらいの報酬が得られるのかをあらわします。株の売買の例では、売買の結果の儲けにあたります。

> ここで、報酬に関しては一点注意が必要です。
先ほど言った通り、強化学習ではその時点で貰える報酬（即時報酬などと呼びます）ではなく、（将来に渡る）価値を最大化します。
よって、単に即時報酬が多くもらえる近視眼的な行動ではなく、より未来を考えた価値を最大化する行動を取らなければなりません。

**Comment by jochaken** [comment]
## ゲーム木とモンテカルロ法を組み合わせる理由
### 3目並べのゲーム木
![b](https://user-images.githubusercontent.com/38747501/59321470-1fda4400-8d0d-11e9-8a80-05d2f68d03fd.png)

> ゲーム木は上から下に読んでいきます。図で状況を表している部分が「ノード」、「ノード」と「ノード」を繋いでいる線の部分が「エッジ」です。一番上のノードを「根ノード（root node）」と呼びます（図の赤い部分）。下の方にある緑の部分では、×が３つ並んでおり、後手の勝ちとなっています。勝敗がついているため、このノードはゲームの終着点であり、このノードから出ていくエッジはありません。このような末端のノードを「葉ノード（leaf node）」と呼びます。

### ゲーム木複雑性という指標
> 途中で省略せず、全ての分岐を葉ノードまで展開したゲーム木のことを完全ゲーム木と呼びます。完全ゲーム木を書くことができれば、そのゲームがどんな風に展開していくのかを全て知ることができるので、そのゲームは先手必勝なのか、後手必勝なのかもわかりますし、実際に勝つための手順も完全に理解することができます。完全ゲーム木の葉ノードが多ければ多いほど、ゲーム展開の分岐が多い複雑なゲームであると解釈することができるため、完全ゲーム木の葉ノードの数をゲーム木複雑性と呼び、ゲームの複雑度の一つの指標とされます。

### 不完全なゲーム木で判断する
> 3目並べのゲーム木複雑性は26,830だそうです。省略せずに書き切って、完全解析できる量ではありますが、このブログに乗せるには大きすぎる数ですね。これもWikipediaの情報ですが、オセロだと10の58乗、チェスだと10の123乗、将棋だと10の226乗、囲碁では10の400乗と見積もられるようです。ここまで複雑なゲームだと、完全ゲーム木を書いて完全解析するというのは、現実的ではないですね。

> そのため、ゲーム木の考えは使いつつ、不完全なゲーム木でより正確な判断をすることが重要となります。ある局面で次に何を指すべきか、パッと有望な候補を絞り込み、その手が本当に有望なのかを、妥当であろう手の応酬である程度盤面を進めてみて、数手後の盤面がどちらにとって有利かという盤面の価値を正確に判断する。そのような能力が求められるわけです。

**Comment by JoeTakasuna** [comment]
## モンテカルロ木探索の5つの要素

1. Selection
2. Expansion
3. Evaluation
4. Backup
5. Play

1~4までが、頭の中で展開を色々シミュレーションしているのに該当し、5が実際の手の選択に該当します。

**Comment by jochaken** [comment]
## モンテカルロ木探索の5つの要素
> 
> 1. Selection
> 2. Expansion
> 3. Evaluation
> 4. Backup
> 5. Play
> 
> 1~4までが、頭の中で展開を色々シミュレーションしているのに該当し、5が実際の手の選択に該当します。

**Comment by JoeTakasuna** [comment]
続きはあすかが書く

**Comment by asuka1107** [comment]
1.Selection：初期状態からどの手を選ぶかをモンテカルロ探索で選択する
2.Expansion：葉ノードを訪れた回数が閾値以上となった場合に、ノードから先を展開する
3.Evaluation：ゲーム木の葉ノードから得られる報酬を評価する
4.Backup：得られた報酬の情報を記録する

5.Play：1~4 の流れを決められた試行回数だけ繰り返し、得られた情報から実行する手を選択する
