### ISSUE TITLE
何も置けない時はパスされるように

### ISSUE THREAD

**Issue by jochaken** [JoeTakasuna/KomatsuBlokus#5]
#4 と密接に関わるので、その担当者がやると良い

**Comment by jochaken** [comment]
#4 と一緒に考えると良さそう

**Comment by jochaken** [comment]
- #4 と同じように事前に探索させる
- ブロック選択の前に探索させて、そもそも候補が0なら自動スキップ

**Comment by jochaken** [comment]
人間は手動パスにする
AIもしくはコンピュータは自動パスにする

**Comment by asuka1107** [comment]
ブロックをキャンセルして、新しく選択しても新しいブロックが切り替わらない
