### ISSUE TITLE
rotatedBlockを各ブロックコンポーネントから除く

### ISSUE THREAD

**Issue by yushun1023** [JoeTakasuna/KomatsuBlokus#60]
*このissueはissue_4の終了後に取り組む。

issue_4の作業中、元々各ブロックコンポーネントにしかなかったrotateBlock関数を、blokus.pyの方にコピーした。
そこで各ブロックコンポーネントからrotateBlock関数を除き、向きが0の状態で形を受け取りblokus.py内で向きを変換させるようにしたい。

**Comment by jochaken** [comment]
#4

**Comment by jochaken** [comment]
オブジェクト化の課程で解決
